Miscellaneous improvements
render-examples/temporal pull request #2
Opened 2022-02-09 22:28 UTC by hieurender

2022-02-11 19:28 UTC, davidmauskop requested changes
We're nearly there!

When I tried deploying with this branch (non-scaled version) the `app-worker` deploy hung. I'll invite you to the team where I tested.

2022-02-11 19:28 UTC, davidmauskop commented on README.md
> +- When deploying for the first time, if the blueprint sync hangs more than 10 minutes waiting for the `temporal-elasticsearch` service, simply trigger a "Manual Sync" in the top right.
We should explain why this might be necessary

2022-02-11 19:28 UTC, davidmauskop commented on README.md
> +    ```
```suggestion
- To use `tctl`, the Temporal CLI, with `render.with_scaling.yaml`, use the temporal-frontend service via the Render web shell or SSH.
```

2022-02-11 19:28 UTC, davidmauskop commented on temporal-cluster/server/entrypoint_override.sh
> +export PUBLIC_FRONTEND_ADDRESS="${PUBLIC_FRONTEND_ADDRESS:-${RENDER_FRONTEND_HOST}:7233}"
If this is the only change to the file, maybe we should use temporal's entrypoint.sh file as is and just change the `ENTRYPOINT` command in the Dockerfile, like we do with the `temporal-ui` service.

2022-02-11 19:28 UTC, davidmauskop commented on render.with_scaling.yaml
> +      - key: RENDER_FRONTEND_HOST
We tend to reserve `RENDER_*` for env vars that Render automatically sets in the environment: https://render.com/docs/environment-variables
```suggestion
      - key: TEMPORAL_FRONTEND_HOST
```

2022-02-24 18:55 UTC, hieurender commented
I'll open the PR to temporalio/temporal-render-simple after merging this, as that PR will link to this repo.

2022-02-24 21:28 UTC, davidmauskop approved these changes
Great stuff!

One last (optional) thought: could we reduce duplication in the render.yaml file by putting env vars that are shared among the four services into an env group?

2022-02-24 22:14 UTC, hieurender commented
@davidmauskop Done!

2022-02-24 22:14 UTC, davidmauskop commented
🎉

2022-02-24 22:21 UTC, merged